[package]
name = "nvidia-uvm-reload"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.6"
dbus-crossroads = "0.5.1"
duct = "0.13.5"

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"